language: node_js
node_js:
- node
sudo: false
install:
- npm i
- npm i -g mocha
before_script:
- psql -c "create database $DB_NAME;" -U $DB_LOGIN
script:
- npm run test
services:
- postgresql
cache:
  directories:
  - node_modules
env:
  global:
  - secure: knPaLGVnJJ57g3tXxRStZ+2IEtMkGlwqCNFn8RnZX+ArQI7SA8QZP3pHyOl3iCiAsW7lHAFhcCddnrjtoHY066dqZLkUzsvZv1pz0lKqQlVYy7C5E7vjBcJ+hDGkiSU0A5mK+kbNHI1sZ6g3tyS/9k9hwK/RHmKucWcXOFF03uUKAlmDjnCCkkJ/arbqz8A7IZofTP6lEIWUTtDMThYGguPnOiXOaKKPK76ywkAichUdDOY+E9qC8myJf23FfJlYyOSzf7/cVT8nRHAbF4HgQ7CH7tne8nu6C627YvlZs9gG7PiLAGYheo7w8vlLfi13dNjJSMvOX541mkAdXy/TAGZr8YUTZzLbQjmWTVAKb3vyDDETa/AwbVKvcZpDDn1RS4J3vl9vt7zvFg8y7/IboDPrxxRv0MJzAtGtTPKRWB6bhKi2u/H3HKify12m2ipm4HoWpHP0gzeSEcX0eTPjYdhAyD040wkM0KNA7FmqurONscGf72+j2FO444FHq6z+tjiyCOOjpYCELGFVpYjiSX7WWXU+v+Cr3lPnpFA1QNNRGNV53KWj8fQbCemVTEskCvim1Im/wc2w9KUjoDPHcCy6ujaT0mybGXJ8THzwYR/VQc3MdcIkE2GCElRP168qKuPivYpuDk40hhG7eP6f1iRhV+08g1tEhvKQTcIyIcE=
  - secure: zF5rFIHq222LP22qN6+R1m17/OsreJfJngDlbhCDLo39JiT1Q6l7paDSLsvEwtRplyV1wNx7yoDTNDavlneW5ILrjp3yE6+tOepa3YwAZzqLPIDNlHCOXGxLpx5hHKLT0qqKYuuxMegPWoL4aLbK9i5pZJqtZaK1DJSCN4PmpiB7iK4te1wSYmIFLFcjX74PIuLjnjp6Vk1pdlKr5jcBR1UYT4PESa+JdAlvLOPba0r35EwbrxpUTqWMPZTufM7oT7Xw90cb1BxSjxkFZ2KpVmXdo1DA5oLF/diApJuhKrqr9l+6N6CH3ixk398I2f7mVWRyC9eftL1nbajfpkyDTw9DKINmKhNSGy2ajA4TkDjWA1nTBCzTyPYsgF24z0ppnYSHrt+94FwQl6xWb9+c8amTRtowcJHbMdg3lwLibOP9ZiyFUMUC9eTgJsJY35vm1oZ83nv7P5idv3Fyr3+pDK94y1GNnknEKGH5kK/uAJDeoHCEiEQWvcZOilX9gSl9PGaRz9DahPG6hoaDpUMkuXKRj0lgnJd5flSMRmEdGuJ817TyiyKKs3GUHz1iR/l7+TYiaMgUFcqCO0O+RKKBA7QBeG0AaLltcA/yCHjyuu6IIzipSJvrFS6AOVLaaPa2UxtORTpPaSyaHu1hXoitbl2Sinr1dsVjzxUC9f1+k3Y=
